meta_product_name: "FIB__R"
meta_title: "FIB__R - CHECK THE QUALITY OF YOUR CLOTHES"
twitter_account: "@product_twitter_account"
meta_description: "CHECK THE QUALITY OF YOUR CLOTHES"
meta_image: "cover.png"
